[Issue #4 : Feature/groups] 독서모임 API (그룹생성, 유저 추가/삭제)
darakbooks-project/darakbooks-BE pull request #7
Opened 2023-05-29 12:29 UTC by shljessie

# 독서모임 api  `/groups`
Issue: #4 

### 기능 요약
> - 그룹생성: `POST /groups`
> - 그룹조회:` GET /groups`
>  - top3 그룹조회:` GET /groups/top/3`
> - 그룹삭제` DELETE /groups/{group_id}`
> - 그룹수정:` PATCH /groups/{group_id}`
> - 특정그룹조회: `GET /groups/{group_id}`
> - 특정그룹장조회: `GET /groups/group_lead/{group_id}`
> - 그룹 유저 조회: `GET /groups/{group_id}/users`
> - 그룹 유저 추가: `POST /groups/{group_id}/add-user/{user_id}`
> - 그룹 유저 삭제: `DELETE /groups/{group_id}/delete-user/{user_id}`

swagger 캡처
![Screenshot 2023-06-01 at 11 22 53 AM](https://github.com/dugeun-dugeun-project/backend_nest/assets/59305253/c873f2e6-64b5-459d-982d-95ccaa29590b)

## 작업 사항(승희)
>  - top3 그룹조회:` GET /groups/top3`
> - 그룹삭제` DELETE /groups/{group_id}`
> - 그룹수정:` PATCH /groups/{group_id}`
> - 특정그룹장조회: `GET /groups/group_lead/{group_id}`
> - 그룹 유저 조회: `GET /groups/{group_id}/users`
> - 그룹 유저 추가: `POST /groups/{group_id}/add-user/{user_id}`
> - 그룹 유저 삭제: `DELETE /groups/{group_id}/delete-user/{user_id}`

## 작업 사항(승완)
> - 그룹생성: `POST /groups`
> - 그룹조회:` GET /groups`
> - 특정그룹조회: `GET /groups/{group_id}`

## 추후 계획
- Postman , API 작동확인

## reference
https://docs.nestjs.com/recipes/sql-typeorm#repository-pattern

2023-05-29 13:22 UTC, shljessie commented
논의 사항

- user 를 group에서 추가/삭제 하는 기능을 groups.service 에 만들었습니다. groups 에서 만 user 추가/삭제 기능을 만들어도 될까요?

2023-05-30 07:34 UTC, shljessie commented
**회의 노트**
- https://www.postman.com/ : API 요청 확인하기 
- group owner 추가
- group 수정, 추가
- top3 group

2023-05-30 09:18 UTC, shljessie commented
5/30
- top3 usrs,editdelete groups, group lead 완료

질문
-how to add users

2023-06-01 10:44 UTC, jyjyjy17 requested changes

2023-06-01 10:44 UTC, jyjyjy17 commented on src/user-group/entities/user-group.entity.ts
> +import { Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
[파일 이동] entities 폴더를 user-group 밖에 만들어서 user-group.entity.ts랑 user-group.provider.ts 옮겨 주세용

2023-06-01 10:44 UTC, jyjyjy17 commented on src/groups/dto/groups.create.dto.ts
> +export class GroupsCreateDto extends PickType(GroupEntity, [
[수정, 질문]class-validator로 각 값 확인해야 합니당 entity 별 제대로 들어왔는지, 필수값 등등!
혹은 picktype을 사용하면 class-validator로 확인 필요 없이 자동 확인하고 client에 잘못 들어왔을 때 exception을 던져주는 걸까요?  
[질문] 그리고 region 어떻게 받기로 했는지 front랑 확인하셨을까용? 기획적인 부분이긴 한데 지역의 어느동까지 받는지 궁금해서요!

2023-06-01 10:44 UTC, jyjyjy17 commented on src/groups/groups.service.ts
> +    const group = new GroupEntity();
[수정] 저렇게 일일이 작성하지 않고 save(dto) 넣으면 각 property 이름 확인하고 자동으로 매핑 시켜줄거에요

2023-06-01 10:44 UTC, jyjyjy17 commented on src/groups/dto/groups.create.dto.ts
> +] as const) {}
[수정] pick type을 사용하지 않는다면 extends 하지 않고 as const) {} 안쓰고 그냥 class 형태 그대로 해도 될거에요 
[질문] pickType을 사용한 이유가 있을까요?

2023-06-01 10:44 UTC, jyjyjy17 commented on src/groups/entities/groups.entity.ts
> +  @ApiProperty({
[수정] 그룹장 id 겠죵??
[추가] 승희님, 그리고 특정 사용자의 가입한 그룹들을 보는 마이독서모임 구현은 누가 할까요?0?

2023-06-01 10:44 UTC, jyjyjy17 commented on src/groups/entities/groups.entity.ts
> +    onUpdate: 'CURRENT_TIMESTAMP(0)',
[질문] current_timestamp(0)이 뭘 의미하는걸까요? 저도 이거 넣으면 될까요?ㅎㅎ

2023-06-01 10:44 UTC, jyjyjy17 commented on src/groups/groups.controller.ts
> +    return await this.groupsService.deleteGroup(groupId);
[수정] 승희님 return body에 아무것도 포함되어 있지 않은 경우 http status를 204로 해서 return 하는게 좋습니다 
res.status(204).send() 이런식으로요!

2023-06-01 10:44 UTC, jyjyjy17 commented on src/groups/groups.controller.ts
> +    return await this.groupsService.createGroup(body);
[수정] 여기도 아마 실제 status는 201이 아니라 200일거같아요 
기본 return 만 사용하면 nestJs는 200으로 인식하거든요! 저도 고쳐야 하는데 차차 고치면 될 거 같아요

2023-06-01 10:44 UTC, jyjyjy17 commented on src/groups/groups.service.ts
> +    if (!group) {
[수정] [우선순위 낮음] excpetionfilter를 controller에서 usefilter로 추가하시고 제가 exceptionfilter에 정의한 notfoundexception을 사용해도 좋을 거 같습니다 
이건 나중에 같이 리팩토링 해요 ㅎㅎ

2023-06-01 10:44 UTC, jyjyjy17 commented on src/groups/groups.service.ts
> +    const group = await this.groupsRepository.findOne({
[수정] const group = await this.groupsRepository.findOne({
      where: { group_id },
      relations: ['userGroup'],
    });
    이 내용을 extract method 해서 findGroupById 로 바꾸면 어떨까요?
    
     if (!group) {
      throw new NotFoundException('해당 독서모임 정보가 존재하지 않습니다.');
    }

이거까지 같이 빼면 좋을 거 같네용 ㅎㅎ

2023-06-01 10:44 UTC, jyjyjy17 commented on src/groups/groups.service.ts
> +    group.name = body.name;
[수정] updateDTO를 createDTO의 PartialType으로 추가해도 좋을 거 같아요~
그대로 dto를 save에 전달하면 확인후 바뀐 사항만 update 돼서 patch request로 받아도 될 거 같습니다

2023-06-01 10:44 UTC, jyjyjy17 commented on src/groups/groups.service.ts
> +    const userfind = await this.userRepository.findOne({
[수정] 이 부분도 removeuser랑 겹치니까 findUser로 빼는게 좋을 거 같아요 
한 메소드에 최대한 한가지 일만 하게 만들어줍시당

2023-06-01 10:57 UTC, jyjyjy17 requested changes

2023-06-01 10:57 UTC, jyjyjy17 commented on src/groups/groups.service.ts
> +    group.name = body.name;
[수정] updateDTO를 createDTO의 PartialType으로 새로 만들어서 추가해도 좋을 거 같아요~
이렇게 하면 update value도 정상적으로 client에서 왔는지 확인 가능하고 
그대로 dto를 save에 전달하면 확인후 바뀐 사항만 update 돼서 patch request로 받아도 될 거 같습니다

2023-06-01 10:57 UTC, jyjyjy17 commented on src/groups/entities/groups.entity.ts
> +  @ApiProperty({
[수정] 그룹장 id 겠죵??
[추가] 승희님, 그리고 특정 사용자의 가입한 그룹들을 보는 마이독서모임 구현은 누가 할까요?0?

2023-06-01 10:57 UTC, jyjyjy17 commented on src/groups/groups.service.ts
> +
[수정] [우선순위 낮음] excpetionfilter를 controller에서 usefilter로 추가하시고 제가 exceptionfilter에 정의한 notfoundexception을 사용해도 좋을 거 같습니다
이건 나중에 같이 리팩토링 해요 ㅎㅎ

2023-06-01 10:57 UTC, jyjyjy17 commented on src/groups/groups.service.ts
> +    const group = new GroupEntity();
[수정] 저렇게 일일이 매핑하지 않고 save(dto) 넣으면 각 property 이름 확인하고 자동으로 매핑 시켜줄거에요

2023-06-01 10:57 UTC, jyjyjy17 commented on src/groups/groups.service.ts
> +    }
[수정] 이 부분도 removeuser랑 adduserTogroup?이랑 겹치니까 findUser로 빼는게 좋을 거 같아요
한 메소드에 최대한 한가지 일만 하게 만들어줍시당

2023-06-02 11:06 UTC, shljessie commented on src/user-group/entities/user-group.entity.ts
> +import { Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
src 
|_ entity
     |_ user-group.entity.ts
     |_ user-group.provider.ts

이렇게요?? @jyjyjy17

2023-06-02 11:20 UTC, shljessie commented on src/groups/dto/groups.create.dto.ts
> +export class GroupsCreateDto extends PickType(GroupEntity, [
[수정, 질문]

이부분은 승완님이 만드신부분 인데요, 찾아보니까 pickType을 사용하여 필요한 필드만 추출하여 유효성 검사를 수행할 수 있는것 같아요. 
- https://github.com/typestack/class-validator/issues/1031 
- https://stackoverflow.com/questions/64788362/typescript-how-can-i-validate-specific-fields-in-child-class-using-class-valid 
- PickType Documentation: https://docs.nestjs.com/openapi/mapped-types 

[질문] 
```
  @ApiProperty({
    example: '서울 강서구',
    description: '모임 장소',
  })
  @Column()
  region: string;
```
프론트에 말씀드렸습니당! string 이여서 dropdown 이나 select 으로 해야할것 같네요!

2023-06-02 11:25 UTC, shljessie commented on src/groups/dto/groups.create.dto.ts
> +] as const) {}
** 위 코멘트랑 같습니다! `userGroup` 때문일까요? userGroup 생성은 독서모임생성 할때 만들어지는게 아니라  나중에 유저가 추가하는거니까 userGroup 을 저기서 빼기 위한것일까요? 저기서 userGroup은 제가 추가했습니다! (원래는 없었어요!)

2023-06-02 11:25 UTC, shljessie commented on src/groups/groups.controller.ts
> +    return await this.groupsService.deleteGroup(groupId);
넵!

2023-06-02 11:46 UTC, shljessie commented on src/groups/entities/groups.entity.ts
> +    onUpdate: 'CURRENT_TIMESTAMP(0)',
이부분도 승완님이요! 
찾아보니까... 

데이터베이스 열 정의의 맥락에서, CURRENT_TIMESTAMP(0)은 현재 날짜와 시간을 타임스탬프로 반환하는 함수입니다. 괄호 안에 있는 (0)은 타임스탬프의 정밀도 또는 소수점 이하 초 단위를 지정합니다.

CURRENT_TIMESTAMP(0)을 지정함으로써, 타임스탬프는 소수점 이하 초를 포함하지 않고 가장 가까운 초로 반올림됩니다. 이는 날짜 및 시간 값에 소수점 이하 초를 저장할 필요가 없거나 원치 않을 때 유용할 수 있습니다.

예를 들어, 현재 날짜와 시간이 2023년 6월 2일 10시 30분 45.123초인 경우, CURRENT_TIMESTAMP(0)을 사용하면 2023년 6월 2일 10시 30분 45초의 값이 반환됩니다.

CURRENT_TIMESTAMP(0)의 정확한 동작은 사용하는 데이터베이스 관리 시스템(DBMS)에 따라 다를 수 있습니다. 다른 DBMS마다 CURRENT_TIMESTAMP 함수의 구문이나 동작에 차이가 있을 수 있으므로 정확한 세부 사항은 작업하는 특정 DBMS의 문서를 참조하는 것이 좋습니다.

2023-06-02 11:53 UTC, shljessie commented on src/groups/groups.service.ts
> +    const group = await this.groupsRepository.findOne({
userGroup 이 manyTomany 여서 findGroupById 해서 group.userGroup 하면 아무것도 안떠요! relations : : ['userGroup'] 을해야 userGroup relations 을 받을 수 있는것 같아요!

2023-06-02 11:56 UTC, shljessie commented on src/groups/entities/groups.entity.ts
> +  @ApiProperty({
승희님, 그리고 특정 사용자의 가입한 그룹들을 보는 마이독서모임 구현은 누가 할까요?0?  --제가 할게요!

2023-06-02 12:16 UTC, shljessie commented on src/groups/groups.service.ts
> +    group.name = body.name;
넵수정했습니다!

2023-06-02 12:16 UTC, jyjyjy17 commented on src/user-group/entities/user-group.entity.ts
> +import { Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
아 승희님 이거는 그냥 제가 파일 받아서 수정할게요 ㅎㅎ

2023-06-02 12:17 UTC, jyjyjy17 commented on src/groups/dto/groups.create.dto.ts
> +] as const) {}
아 승희님 제가 말씀드린건 
import { IsArray, IsString } from 'class-validator';

export class BookDTO {
    @IsString()
    bookIsbn: string;
  
    @IsString()
    title: string;
  
    @IsArray()
    thumbnail: string;

}
이런식으로 class-validator로 값 확인 해주는거요!!

2023-06-02 12:18 UTC, jyjyjy17 commented on src/groups/entities/groups.entity.ts
> +    onUpdate: 'CURRENT_TIMESTAMP(0)',
넹 ㅎㅎ 저도 넣을게요~

2023-06-02 12:20 UTC, jyjyjy17 commented on src/groups/groups.service.ts
> +    const group = await this.groupsRepository.findOne({
넹넹!
그러니까 저 부분을 원래 있던 getUsergroup 밖으로 메소드를 하나 더 만들면 어떨가요?ㅎㅎ
저 명령이 두군데에서 겹치더라구요!

2023-06-02 12:57 UTC, shljessie commented on src/groups/groups.service.ts
> +    }
넵 수정했습니다!

2023-06-02 13:03 UTC, shljessie commented on src/groups/dto/groups.create.dto.ts
> +] as const) {}
넵 그건 이해했습니다! 그럼 지금 `ReadOnlyGroupsDto` 랑 `GroupsCreateDto` 이 같으니까그냥 하나로 통일할까요?

2023-06-02 13:03 UTC, shljessie commented on src/groups/groups.service.ts
> +    const group = await this.groupsRepository.findOne({
넵 그렇게 수정했어요! ㅎㅎ

2023-06-04 11:49 UTC, jyjyjy17 commented on src/groups/dto/groups.create.dto.ts
> +] as const) {}
네!!

2023-06-04 11:53 UTC, jyjyjy17 approved these changes

2023-06-04 11:53 UTC, merged